---
name: Try a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_release_dry_run_callable.yml@aa06a3d8a580efc719d66bafdcb5d2ca6613cdea
    secrets: inherit
