---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_spelling_callable.yml@13628b3a168ca0096a52ecf93fa1a92295580a9f
    secrets: inherit
